php?>
 <html><body>
<p>This is a paragraph.</p>
</body></html>
echo "<?P\n?>"
echo "echo \"<?P\n\nP>"
echo ";"<!DOCTYPE html>\\n\";\n";
echo "echo \"<html>\\n\";\n";
echo "echo \"<head>\\n\";\n";
echo "echo \"<meta http-equiv=\\\"Content-Type\\\" content=\\\"text/html; charset=utf-8\\\" />\\n\";\n";
echo "echo \"<meta name=\\\"viewport\\\" content=\\\"width=device-width, initial-scale=1.0 , user-scalable=no\\\"/>\\n\";\n";
echo "echo \"<title>The Rougue Den Chat</title>\\n\";\n";
echo "echo \" <meta name=\\\"description\\\" content=\\\"a troll free chat with  hour mods and admin.\\\"><\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"<!-- Loading the jScrollPane CSS, along with the styling of the\\n\";\n";
echo "echo \"     chat in chat.css and the rest of the page in page.css -->\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"<link rel=\\\"stylesheet\\\" type=\\\"text/css\\\" href=\\\"js/jScrollPane/jScrollPane.css\\\" />\\n\";\n";
echo "echo \"<link rel=\\\"stylesheet\\\" type=\\\"text/css\\\" href=\\\"css/page.css\\\" />\\n\";\n";
echo "echo \"         <link rel=\\\"stylesheet\\\" type=\\\"text/css\\\" href=\\\"css/chat.css\\\" />\\n\";\n";
echo "echo \"         <link rel=\\\"stylesheet\\\" href=\\\"https://maxcdn.bootstrapcdn.com/bootstrap/css/bootstrap.min.css\\\" integrity=\\\"sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/68vbdEjh4u\\\" crossorigin=\\\"anonymous\\\">\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \" </head>\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"<body>\\n\";\n";
echo "echo \"div#ritchierich_tools{\\n\";\n";
echo "echo \"    margin:0;padding:0;\\n\";\n";
echo "echo \"    width                                        : auto;\\n\";\n";
echo "echo \"    min-height                                : 11em;\\n\";\n";
echo "echo \"    background-color                :#36393D;\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"div#ritchierich_tools ,\\n\";\n";
echo "echo \"div#ritchierich_tabcontainer{\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"div#ritchierich_chanContainer{\\n\";\n";
echo "echo \"    background-color: #ECECEA;\\n\";\n";
echo "echo \"    height          : 25em;\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"div#ritchierich_usercolors{\\n\";\n";
echo "echo \"    margin:0; padding:0;\\n\";\n";
echo "echo \"    display                                        : none;\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"div#ritchierich_colorlist {\\n\";\n";
echo "echo \"    margin:0; padding:0;\\n\";\n";
echo "echo \"    display                                        : none;\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"div.channel{\\n\";\n";
echo "echo \"    margin: 0;padding: 0;\\n\";\n";
echo "echo \"    position:relative;\\n\";\n";
echo "echo \"    background-image        : url('./images/textarea.png');\\n\";\n";
echo "echo \"    background-repeat       : no-repeat;\\n\";\n";
echo "echo \"    background-position     : 75% 97%;\\n\";\n";
echo "echo \"    background-color        : #EEEEEE;\\n\";\n";
echo "echo \"    border-left             : 1px solid #bbbdbe;\\n\";\n";
echo "echo \"    width                   : 100%;\\n\";\n";
echo "echo \"    height                  : 25em;\\n\";\n";
echo "echo \"    border-right            : 1px solid #bbbdbe;\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"ul.ritchierich_textarea{\\n\";\n";
echo "echo \"    /*margin: 0;padding: 0;*/\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"    /*background-color                : #EBEBEB;\\n\";\n";
echo "echo \"    background-image                : url('../../images/textarea.png');\\n\";\n";
echo "echo \"    background-repeat                : no-repeat;\\n\";\n";
echo "echo \"    background-position                : 96% 50%;*/\\n\";\n";
echo "echo \"    /*width                                    : 78.1%;\\n\";\n";
echo "echo \"    height                  : 25em;\\n\";\n";
echo "echo \"    border-right                        : 1px solid #bbbdbe;\\n\";\n";
echo "echo \"    overflow                            : auto;\\n\";\n";
echo "echo \"    overflow-x                            : hidden;*/\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"      margin:0px;\\n\";\n";
echo "echo \"      padding:0px;\\n\";\n";
echo "echo \"      position:absolute;\\n\";\n";
echo "echo \"      bottom:0px; \\n\";\n";
echo "echo \"      left:0px;\\n\";\n";
echo "echo \"      width:78.2%;\\n\";\n";
echo "echo \"      overflow:hidden;\\n\";\n";
echo "echo \"      overflow-y:scroll;\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"ul.ritchierich_textarea li{\\n\";\n";
echo "echo \"    margin:0;padding:0;\\n\";\n";
echo "echo \"    list-style: none;\\n\";\n";
echo "echo \"    text-decoration: none;\\n\";\n";
echo "echo \"    margin-bottom                        :0.7em;\\n\";\n";
echo "echo \"    margin-left                                :1.5em;\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"/*****nick whois************/\\n\";\n";
echo "echo \"div.ritchierich_nickwhois{\\n\";\n";
echo "echo \"    padding: 0; margin: 0;\\n\";\n";
echo "echo \"    padding                                        : 1em;\\n\";\n";
echo "echo \"    min-width                                : 18em;\\n\";\n";
echo "echo \"    /*background-image                : url('../images/world.png');\\n\";\n";
echo "echo \"    background-repeat                : no-repeat;\\n\";\n";
echo "echo \"    background-position                : center;*/\\n\";\n";
echo "echo \"    font-size                                : 90%;\\n\";\n";
echo "echo \"    -webkit-border-radius        : 10px;\\n\";\n";
echo "echo \"    -moz-border-radius                : 10px;\\n\";\n";
echo "echo \"    border-radius                        : 10px;\\n\";\n";
echo "echo \"    background                                : #CCCCCC;\\n\";\n";
echo "echo \"    background                                : -webkit-gradient(linear, bottom, left 175px, from(#CCCCCC), to(#EEEEEE));\\n\";\n";
echo "echo \"    background                                : -moz-linear-gradient(bottom, #CCCCCC, #EEEEEE 175px);\\n\";\n";
echo "echo \"    filter                                        : progid:DXImageTransform.Microsoft.gradient(startColorstr='#EEEEEE', endColorstr='#CCCCCC'); /* for IE <= 9 */\\n\";\n";
echo "echo \"    background                                : linear-gradient(to bottom, #EEEEEE, #CCCCCC);/*ie10*/\\n\";\n";
echo "echo \"    -webkit-box-shadow                : 0px 0px 8px rgba(0, 0, 0, 0.3);\\n\";\n";
echo "echo \"    -moz-box-shadow                        : 0px 0px 8px rgba(0, 0, 0, 0.3);\\n\";\n";
echo "echo \"    box-shadow                                : 0px 0px 8px rgba(0, 0, 0, 0.3);\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"div.ritchierich_nickwhois a {\\n\";\n";
echo "echo \"    text-decoration                               : none;\\n\";\n";
echo "echo \"    display                                       : block;\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"div.ritchierich_nickwhois a:hover {\\n\";\n";
echo "echo \"    text-decoration                               : underline;\\n\";\n";
echo "echo \"    cursor                                        : pointer;\\n\";\n";
echo "echo \"    color                                                : #356AA0;\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"div.ritchierich_nickwhois a img { border: none; }\\n\";\n";
echo "echo \"p.ritchierich_nickwhois_header {\\n\";\n";
echo "echo \"    margin: 0; padding: 0;\\n\";\n";
echo "echo \"    background-color                        : #6DBDD6;\\n\";\n";
echo "echo \"    border-bottom                                : 1px solid #444;\\n\";\n";
echo "echo \"    text-align                                : center;\\n\";\n";
echo "echo \"    font-weight                                : bold;\\n\";\n";
echo "echo \"    vertical-align                        : middle;\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"div#pic header{\\n\";\n";
echo "echo \"    text-align                          :center;\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"img.ritchierich_close{\\n\";\n";
echo "echo \"    float                                        : left;\\n\";\n";
echo "echo \"    cursor                                        : pointer;\\n\";\n";
echo "echo \"    vertical-align          : middle;\\n\";\n";
echo "echo \"    margin                                        : 3px 0 3px 2px;\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"p.ritchierich_nickwhois_ip{\\n\";\n";
echo "echo \"    text-align                                : center;\\n\";\n";
echo "echo \"    color                                        : #3F4C6B;\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"/*************** lists ***********************************/\\n\";\n";
echo "echo \"div.ritchierich_userlist{\\n\";\n";
echo "echo \"    margin: 0;padding: 0;\\n\";\n";
echo "echo \"    float                                    :        right;\\n\";\n";
echo "echo \"    /*background-image                :        url('../../images/nicklist.png');\\n\";\n";
echo "echo \"    background-repeat                :         no-repeat;\\n\";\n";
echo "echo \"    background-position                :         bottom;\\n\";\n";
echo "echo \"    background-color        :   #F6F6F6;*/\\n\";\n";
echo "echo \"    border-left                                :   1px solid #413546;\\n\";\n";
echo "echo \"    width                                        :   21.5%;\\n\";\n";
echo "echo \"    overflow                                :   auto;\\n\";\n";
echo "echo \"    height                  :   25em;\\n\";\n";
echo "echo \"    overflow-x                                :   hidden;\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"ul.ritchierich_textarea a.nickRef{\\n\";\n";
echo "echo \"    text-decoration                             : none;\\n\";\n";
echo "echo \"    padding                                 : 0.5em;\\n\";\n";
echo "echo \"    cursor                                        : pointer;\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"div.ritchierich_user{\\n\";\n";
echo "echo \"    padding                 : 0;margin:0;\\n\";\n";
echo "echo \"    margin                                        : 10px 0 4px 0;\\n\";\n";
echo "echo \"    border-bottom           : 1px solid #AAA;\\n\";\n";
echo "echo \"    width                                        : 100%;\\n\";\n";
echo "echo \"    height                                        : 30px;\\n\";\n";
echo "echo \"    background-image                        : none;\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"div.ritchierich_user a{\\n\";\n";
echo "echo \"    color                                        :#000;\\n\";\n";
echo "echo \"    text-decoration                         :none;\\n\";\n";
echo "echo \"    cursor                                        : pointer;\\n\";\n";
echo "echo \"    margin-left                                :6px;\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"img.user_emo{\\n\";\n";
echo "echo \"    margin: 0; padding: 0;\\n\";\n";
echo "echo \"    float                                        :left;\\n\";\n";
echo "echo \"    border                                        :none;\\n\";\n";
echo "echo \"    /*margin-top:-3px;*/\\n\";\n";
echo "echo \"    margin-left                                :12px;\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"/** Profile area **/\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"ul.ritchierich_userPorfile{\\n\";\n";
echo "echo \"    list-style-type: none;\\n\";\n";
echo "echo \"    padding: 0px;\\n\";\n";
echo "echo \"    margin: 0px;\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"ul.ritchierich_userPorfile li{\\n\";\n";
echo "echo \"    background-image: url('./images/sqpurple.gif');\\n\";\n";
echo "echo \"    background-repeat: no-repeat;\\n\";\n";
echo "echo \"    background-position: 0px 5px;\\n\";\n";
echo "echo \"    padding-left: 14px;\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"/************ text area **************************************/\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"textarea#ritchierich_msgfield{\\n\";\n";
echo "echo \"    -webkit-box-sizing: border-box;\\n\";\n";
echo "echo \"    -moz-box-sizing: border-box;\\n\";\n";
echo "echo \"    box-sizing: border-box;\\n\";\n";
echo "echo \"    height: 3em;\\n\";\n";
echo "echo \"    width: 100%;\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"/****************smilyes********************************/\\n\";\n";
echo "echo \"div#ritchierich_smiley_container {\\n\";\n";
echo "echo \"    margin: 0; padding: 0;\\n\";\n";
echo "echo \"    margin-left                                : 1em;\\n\";\n";
echo "echo \"    margin-right                                : 1em;\\n\";\n";
echo "echo \"    width                                        : auto;\\n\";\n";
echo "echo \"    background-color                        : #FFF;\\n\";\n";
echo "echo \"    border                                : 1px solid #555;\\n\";\n";
echo "echo \"    padding                                : 4px;\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"div#ritchierich_smiley_container img.ritchierich_smileys {\\n\";\n";
echo "echo \"    margin: 0; padding: 0;\\n\";\n";
echo "echo \"    margin-right                        : 5px;\\n\";\n";
echo "echo \"    cursor                                    : pointer;\\n\";\n";
echo "echo \"    vertical-align                        : middle;\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"/*-----------------system names-------------------------*/\\n\";\n";
echo "echo \"span.sys_name{\\n\";\n";
echo "echo \"    color                                        : #FF0084;\\n\";\n";
echo "echo \"    font-style                                : italic;\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"span.userJoin{\\n\";\n";
echo "echo \"    color                                       : #73880A;\\n\";\n";
echo "echo \"    font-style                                  : italic;\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"span.announcement{\\n\";\n";
echo "echo \"    color                                        : #890E0E;\\n\";\n";
echo "echo \"    font-style                                  : italic;\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"span.userLef{\\n\";\n";
echo "echo \"    color                                        : #CC0000;\\n\";\n";
echo "echo \"    font-style                                  : italic;\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"span.userBan ,\\n\";\n";
echo "echo \"span.userKick,\\n\";\n";
echo "echo \"span.userGagg,\\n\";\n";
echo "echo \"span.userUngagged{\\n\";\n";
echo "echo \"    color                                        : #CC0000;\\n\";\n";
echo "echo \"    font-style                                : italic;\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"span.sys_msg_setaway{\\n\";\n";
echo "echo \"    color                                        : #bebebe;\\n\";\n";
echo "echo \"    font-style                                : italic;\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"span.ritchierich_date{\\n\";\n";
echo "echo \"    float                                        : right;\\n\";\n";
echo "echo \"    color                                        : #bebebe;\\n\";\n";
echo "echo \"    font-size                                   : 70%;\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"div.ritchierich_message{\\n\";\n";
echo "echo \"    width                                        :98%;\\n\";\n";
echo "echo \"    margin-bottom                           :0.5em;\\n\";\n";
echo "echo \"    margin-left                                :1.5em;\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"/*****************buttons*************************************************/\\n\";\n";
echo "echo \"div#ritchierich_button_container{\\n\";\n";
echo "echo \"    margin-left                        : 1em;\\n\";\n";
echo "echo \"    margin-right                        : 1em;\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"div.ritchierich_btn{\\n\";\n";
echo "echo \"    margin: 0; padding: 0;\\n\";\n";
echo "echo \"    display                                : inline;\\n\";\n";
echo "echo \"    cursor                                : pointer;\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"div.ritchierich_btn img {\\n\";\n";
echo "echo \"    margin: 0; padding: 2px; border: none;\\n\";\n";
echo "echo \"    vertical-align                        : middle;\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"</div>\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"<!-- Loading jQuery, the mousewheel plugin and jScrollPane, along with our script.js -->\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"<script src=\\\"http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js\\\"></script>\\n\";\n";
echo "echo \"<script src=\\\"js/jScrollPane/jquery.mousewheel.js\\\"></script>\\n\";\n";
echo "echo \"<script src=\\\"js/jScrollPane/jScrollPane.min.js\\\"></script>\\n\";\n";
echo "echo \"<script src=\\\"js/script.js\\\"></script>\\n\";\n";
echo "echo \"</body>\\n\";\n";
echo "echo \"</html>\\n\";\n";
echo "echo \"require \\\"classes/DB.class.php\\\";\\n\";\n";
echo "echo \"require \\\"classes/Chat.class.php\\\";\\n\";\n";
echo "echo \"require \\\"classes/ChatBase.class.php\\\";\\n\";\n";
echo "echo \"require \\\"classes/ChatLine.class.php\\\";\\n\";\n";
echo "echo \"require \\\"classes/ChatUser.class.php\\\";\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"session_name('webchat');\\n\";\n";
echo "echo \"session_start();\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"if(get_magic_quotes_gpc()){\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"    // If magic quotes is enabled, strip the extra slashes\\n\";\n";
echo "echo \"    array_walk_recursive($_GET,create_function('&$v,$k','$v = stripslashes($v);'));\\n\";\n";
echo "echo \"    array_walk_recursive($_POST,create_function('&$v,$k','$v = stripslashes($v);'));\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"try{\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"    // Connecting to the database\\n\";\n";
echo "echo \"    DB::init($dbOptions);\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"    $response = array();\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"    // Handling the supported actions:\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"    switch($_GET[action]){\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        case 'login':\\n\";\n";
echo "echo \"            $response = Chat::login($_POST[name],$_POST[email]);\\n\";\n";
echo "echo \"        break;\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        case 'checkLogged':\\n\";\n";
echo "echo \"            $response = Chat::checkLogged();\\n\";\n";
echo "echo \"        break;\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        case 'logout':\\n\";\n";
echo "echo \"            $response = Chat::logout();\\n\";\n";
echo "echo \"        break;\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        case 'submitChat':\\n\";\n";
echo "echo \"            $response = Chat::submitChat($_POST[chatText]);\\n\";\n";
echo "echo \"        break;\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        case 'getUsers':\\n\";\n";
echo "echo \"            $response = Chat::getUsers();\\n\";\n";
echo "echo \"        break;\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        case 'getChats':\\n\";\n";
echo "echo \"            $response = Chat::getChats($_GET[lastID]);\\n\";\n";
echo "echo \"        break;\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        default:\\n\";\n";
echo "echo \"            throw new Exception('Wrong action');\\n\";\n";
echo "echo \"    }\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"    echo json_encode($response);\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"catch(Exception $e){\\n\";\n";
echo "echo \"    die(json_encode(array('error' => $e->getMessage())));\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"class DB {\\n\";\n";
echo "echo \"        private static $instance;\\n\";\n";
echo "echo \"        private $MySQLi;\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        private function __construct(array $dbOptions){\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"                $this->MySQLi = @ new mysqli(        $dbOptions[db_host],\\n\";\n";
echo "echo \"                                                                               $dbOptions[db_user],\\n\";\n";
echo "echo \"                                                                                $dbOptions[db_pass],\\n\";\n";
echo "echo \"                                                                                $dbOptions[db_name] );\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"                if (mysqli_connect_errno()) {\\n\";\n";
echo "echo \"                        throw new Exception('Database error.');\\n\";\n";
echo "echo \"                }\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"                $this->MySQLi->set_charset(\\\"utf8\\\");\\n\";\n";
echo "echo \"        }\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        public static function init(array $dbOptions){\\n\";\n";
echo "echo \"                if(self::$instance instanceof self){\\n\";\n";
echo "echo \"                        return false;\\n\";\n";
echo "echo \"                }\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"                self::$instance = new self($dbOptions);\\n\";\n";
echo "echo \"        }\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        public static function getMySQLiObject(){\\n\";\n";
echo "echo \"                return self::$instance->MySQLi;\\n\";\n";
echo "echo \"        }\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        public static function query($q){\\n\";\n";
echo "echo \"                return self::$instance->MySQLi->query($q);\\n\";\n";
echo "echo \"        }\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        public static function esc($str){\\n\";\n";
echo "echo \"                return self::$instance->MySQLi->real_escape_string(htmlspecialchars($str));\\n\";\n";
echo "echo \"        }\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"/* This is the base class, used by both ChatLine and ChatUser */\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"class ChatBase{\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"    // This constructor is used by all the chat classes:\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"    public function __construct(array $options){\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        foreach($options as $k=>$v){\\n\";\n";
echo "echo \"            if(isset($this->$k)){\\n\";\n";
echo "echo \"                $this->$k = $v;\\n\";\n";
echo "echo \"            }\\n\";\n";
echo "echo \"        }\\n\";\n";
echo "echo \"    }\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"* Chat line is used for the chat entries */\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"class ChatLine extends ChatBase{\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"    protected $text = '', $author = '', $gravatar = '';\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"    public function save(){\\n\";\n";
echo "echo \"        DB::query(\\\"\\n\";\n";
echo "echo \"            INSERT INTO webchat_lines (author, gravatar, text)\\n\";\n";
echo "echo \"            VALUES (\\n\";\n";
echo "echo \"                '\\\".DB::esc($this->author).\\\"',\\n\";\n";
echo "echo \"                '\\\".DB::esc($this->gravatar).\\\"',\\n\";\n";
echo "echo \"                '\\\".DB::esc($this->text).\\\"'\\n\";\n";
echo "echo \"        )\\\");\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        // Returns the MySQLi object of the DB class\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        return DB::getMySQLiObject();\\n\";\n";
echo "echo \"    }\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"class ChatUser extends ChatBase{\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"    protected $name = '', $gravatar = '';\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"    public function save(){\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        DB::query(\\\"\\n\";\n";
echo "echo \"            INSERT INTO webchat_users (name, gravatar)\\n\";\n";
echo "echo \"            VALUES (\\n\";\n";
echo "echo \"                '\\\".DB::esc($this->name).\\\"',\\n\";\n";
echo "echo \"                '\\\".DB::esc($this->gravatar).\\\"'\\n\";\n";
echo "echo \"        )\\\");\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        return DB::getMySQLiObject();\\n\";\n";
echo "echo \"    }\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"    public function update(){\\n\";\n";
echo "echo \"        DB::query(\\\"\\n\";\n";
echo "echo \"            INSERT INTO webchat_users (name, gravatar)\\n\";\n";
echo "echo \"            VALUES (\\n\";\n";
echo "echo \"                '\\\".DB::esc($this->name).\\\"',\\n\";\n";
echo "echo \"                '\\\".DB::esc($this->gravatar).\\\"'\\n\";\n";
echo "echo \"            ) ON DUPLICATE KEY UPDATE last_activity = NOW()\\\");\\n\";\n";
echo "echo \"    }\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"/* The Chat class exploses public static methods, used by ajax.php */\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"class Chat{\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"    public static function login($name,$email){\\n\";\n";
echo "echo \"        if(!$name || !$email){\\n\";\n";
echo "echo \"            throw new Exception('Fill in all the required fields.');\\n\";\n";
echo "echo \"        }\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        if(!filter_input(INPUT_POST,'email',FILTER_VALIDATE_EMAIL)){\\n\";\n";
echo "echo \"            throw new Exception('Your email is invalid.');\\n\";\n";
echo "echo \"        }\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        // Preparing the gravatar hash:\\n\";\n";
echo "echo \"        $gravatar = md5(strtolower(trim($email)));\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        $user = new ChatUser(array(\\n\";\n";
echo "echo \"            'name'        => $name,\\n\";\n";
echo "echo \"            'gravatar'    => $gravatar\\n\";\n";
echo "echo \"        ));\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        // The save method returns a MySQLi object\\n\";\n";
echo "echo \"        if($user->save()->affected_rows != 1){\\n\";\n";
echo "echo \"            throw new Exception('This nick is in use.');\\n\";\n";
echo "echo \"        }\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        $_SESSION[user]    = array(\\n\";\n";
echo "echo \"            'name'        => $name,\\n\";\n";
echo "echo \"            'gravatar'    => $gravatar\\n\";\n";
echo "echo \"        );\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        return array(\\n\";\n";
echo "echo \"            'status'    => 1,\\n\";\n";
echo "echo \"            'name'        => $name,\\n\";\n";
echo "echo \"            'gravatar'    => Chat::gravatarFromHash($gravatar)\\n\";\n";
echo "echo \"        );\\n\";\n";
echo "echo \"    }\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"    public static function checkLogged(){\\n\";\n";
echo "echo \"        $response = array('logged' => false);\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        if($_SESSION[user]['name']){\\n\";\n";
echo "echo \"            $response[logged] = true;\\n\";\n";
echo "echo \"            $response[loggedAs] = array(\\n\";\n";
echo "echo \"                'name'        => $_SESSION[user]['name'],\\n\";\n";
echo "echo \"                'gravatar'    => Chat::gravatarFromHash($_SESSION[user]['gravatar'])\\n\";\n";
echo "echo \"            );\\n\";\n";
echo "echo \"        }\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        return $response;\\n\";\n";
echo "echo \"    }\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"    public static function logout(){\\n\";\n";
echo "echo \"        DB::query(\\\"DELETE FROM webchat_users WHERE name = '\\\".DB::esc($_SESSION[user]['name']).\\\"'\\\");\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        $_SESSION = array();\\n\";\n";
echo "echo \"        unset($_SESSION);\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        return array('status' => 1);\\n\";\n";
echo "echo \"    }\\n\";\n";
echo "echo \"    public static function submitChat($chatText){\\n\";\n";
echo "echo \"        if(!$_SESSION[user]){\\n\";\n";
echo "echo \"            throw new Exception('You are not logged in');\\n\";\n";
echo "echo \"        }\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        if(!$chatText){\\n\";\n";
echo "echo \"            throw new Exception('You haven\\\\' entered a chat message.');\\n\";\n";
echo "echo \"        }\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        $chat = new ChatLine(array(\\n\";\n";
echo "echo \"            'author'    => $_SESSION[user]['name'],\\n\";\n";
echo "echo \"            'gravatar'    => $_SESSION[user]['gravatar'],\\n\";\n";
echo "echo \"            'text'        => $chatText\\n\";\n";
echo "echo \"        ));\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        // The save method returns a MySQLi object\\n\";\n";
echo "echo \"        $insertID = $chat->save()->insert_id;\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        return array(\\n\";\n";
echo "echo \"            'status'    => 1,\\n\";\n";
echo "echo \"            'insertID'    => $insertID\\n\";\n";
echo "echo \"        );\\n\";\n";
echo "echo \"    }\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"    public static function getUsers(){\\n\";\n";
echo "echo \"        if($_SESSION[user]['name']){\\n\";\n";
echo "echo \"            $user = new ChatUser(array('name' => $_SESSION[user][name]));\\n\";\n";
echo "echo \"            $user->update();\\n\";\n";
echo "echo \"        }\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        // Deleting chats older than 5 minutes and users inactive for 30 seconds\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        DB::query(\\\"DELETE FROM webchat_lines WHERE ts < SUBTIME(NOW(),'0:5:0')\\\");\\n\";\n";
echo "echo \"        DB::query(\\\"DELETE FROM webchat_users WHERE last_activity < SUBTIME(NOW(),'0:0:30')\\\");\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        $result = DB::query('SELECT * FROM webchat_users ORDER BY name ASC LIMIT 18');\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        $users = array();\\n\";\n";
echo "echo \"        while($user = $result->fetch_object()){\\n\";\n";
echo "echo \"            $user->gravatar = Chat::gravatarFromHash($user->gravatar,30);\\n\";\n";
echo "echo \"            $users= $user;\\n\";\n";
echo "echo \"        }\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        return array(\\n\";\n";
echo "echo \"            'users' => $users,\\n\";\n";
echo "echo \"            'total' => DB::query('SELECT COUNT(*) as cnt FROM webchat_users')->fetch_object()->cnt\\n\";\n";
echo "echo \"        );\\n\";\n";
echo "echo \"    }\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"    public static function getChats($lastID){\\n\";\n";
echo "echo \"        $lastID = (int)$lastID;\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        $result = DB::query('SELECT * FROM webchat_lines WHERE id > '.$lastID.' ORDER BY id ASC');\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        $chats = array();\\n\";\n";
echo "echo \"        while($chat = $result->fetch_object()){\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"            // Returning the GMT (UTC) time of the chat creation:\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"            $chat->time = array(\\n\";\n";
echo "echo \"                'hours'        => gmdate('H',strtotime($chat->ts)),\\n\";\n";
echo "echo \"                'minutes'    => gmdate('i',strtotime($chat->ts))\\n\";\n";
echo "echo \"            );\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"            $chat->gravatar = Chat::gravatarFromHash($chat->gravatar);\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"            $chats = $chat;\\n\";\n";
echo "echo \"        }\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        return array('chats' => $chats);\\n\";\n";
echo "echo \"    }\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"    public static function gravatarFromHash($hash, $size=23){\\n\";\n";
echo "echo \"        return 'http://www.gravatar.com/avatar/'.$hash.'?size='.$size.'&default='.\\n\";\n";
echo "echo \"                urlencode('http://www.gravatar.com/avatar/ad516503a11cd5ca435acc9bb6523536?size='.$size);\\n\";\n";
echo "echo \"    }\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"/* Overriding the default styles of jScrollPane */\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \".jspVerticalBar{\\n\";\n";
echo "echo \"    background:none;\\n\";\n";
echo "echo \"    width:20px;\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \".jspTrack{\\n\";\n";
echo "echo \"    background-color:#202020;\\n\";\n";
echo "echo \"    border:1px solid #111111;\\n\";\n";
echo "echo \"    width:3px;\\n\";\n";
echo "echo \"    right:-10px;\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \".jspDrag {\\n\";\n";
echo "echo \"    background:url('../img/slider.png') no-repeat;\\n\";\n";
echo "echo \"    width:20px;\\n\";\n";
echo "echo \"    left:-9px;\\n\";\n";
echo "echo \"    height:20px !important;\\n\";\n";
echo "echo \"    margin-top:-5px;\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \".jspDrag:hover{\\n\";\n";
echo "echo \"    background-position:left bottom;\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"/* Additional styles */\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"    },\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"    // Init binds event listeners and sets up timers:\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"    init : function(){\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        // Using the defaultText jQuery plugin, included at the bottom:\\n\";\n";
echo "echo \"        $('#name').defaultText('Nickname');\\n\";\n";
echo "echo \"        $('#email').defaultText('Email (Gravatars are Enabled)');\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        // Converting the #chatLineHolder div into a jScrollPane,\\n\";\n";
echo "echo \"        // and saving the plugin's API in chat.data:\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        chat.data.jspAPI = $('#chatLineHolder').jScrollPane({\\n\";\n";
echo "echo \"            verticalDragMinHeight: 12,\\n\";\n";
echo "echo \"            verticalDragMaxHeight: 12\\n\";\n";
echo "echo \"        }).data('jsp');\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        // We use the working variable to prevent\\n\";\n";
echo "echo \"        // multiple form submissions:\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        var working = false;\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        // Logging a person in the chat:\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        $('#loginForm').submit(function(){\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"            if(working) return false;\\n\";\n";
echo "echo \"            working = true;\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"            // Using our tzPOST wrapper function\\n\";\n";
echo "echo \"            // (defined in the bottom):\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"            $.tzPOST('login',$(this).serialize(),function(r){\\n\";\n";
echo "echo \"                working = false;\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"                if(r.error){\\n\";\n";
echo "echo \"                    chat.displayError(r.error);\\n\";\n";
echo "echo \"                }\\n\";\n";
echo "echo \"                else chat.login(r.name,r.gravatar);\\n\";\n";
echo "echo \"            });\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"            return false;\\n\";\n";
echo "echo \"        });\\n\";\n";
echo "echo \"  // Submitting a new chat entry:\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        $('#submitForm').submit(function(){\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"            var text = $('#chatText').val();\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"            if(text.length == 0){\\n\";\n";
echo "echo \"                return false;\\n\";\n";
echo "echo \"            }\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"            if(working) return false;\\n\";\n";
echo "echo \"            working = true;\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"            // Assigning a temporary ID to the chat:\\n\";\n";
echo "echo \"            var tempID = 't'+Math.round(Math.random()*1000000),\\n\";\n";
echo "echo \"                params = {\\n\";\n";
echo "echo \"                    id            : tempID,\\n\";\n";
echo "echo \"                    author        : chat.data.name,\\n\";\n";
echo "echo \"                    gravatar    : chat.data.gravatar,\\n\";\n";
echo "echo \"                    text        : text.replace(/</g,'<').replace(/>/g,'>')\\n\";\n";
echo "echo \"                };\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"            // Using our addChatLine method to add the chat\\n\";\n";
echo "echo \"            // to the screen immediately, without waiting for\\n\";\n";
echo "echo \"            // the AJAX request to complete:\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"            chat.addChatLine($.extend({},params));\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"            // Using our tzPOST wrapper method to send the chat\\n\";\n";
echo "echo \"            // via a POST AJAX request:\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"            $.tzPOST('submitChat',$(this).serialize(),function(r){\\n\";\n";
echo "echo \"                working = false;\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"                $('#chatText').val('');\\n\";\n";
echo "echo \"                $('div.chat-'+tempID).remove();\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"                params['id'] = r.insertID;\\n\";\n";
echo "echo \"                chat.addChatLine($.extend({},params));\\n\";\n";
echo "echo \"            });\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"            return false;\\n\";\n";
echo "echo \"        });\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        // Logging the user out:\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        $('a.logoutButton').live('click',function(){\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"            $('#chatTopBar > span').fadeOut(function(){\\n\";\n";
echo "echo \"                $(this).remove();\\n\";\n";
echo "echo \"            });\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"            $('#submitForm').fadeOut(function(){\\n\";\n";
echo "echo \"                $('#loginForm').fadeIn();\\n\";\n";
echo "echo \"            });\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"            $.tzPOST('logout');\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"            return false;\\n\";\n";
echo "echo \"        });\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        // Checking whether the user is already logged (browser refresh)\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        $.tzGET('checkLogged',function(r){\\n\";\n";
echo "echo \"            if(r.logged){\\n\";\n";
echo "echo \"                chat.login(r.loggedAs.name,r.loggedAs.gravatar);\\n\";\n";
echo "echo \"            }\\n\";\n";
echo "echo \"        });\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        // Self executing timeout functions\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        (function getChatsTimeoutFunction(){\\n\";\n";
echo "echo \"            chat.getChats(getChatsTimeoutFunction);\\n\";\n";
echo "echo \"        })();\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        (function getUsersTimeoutFunction(){\\n\";\n";
echo "echo \"            chat.getUsers(getUsersTimeoutFunction);\\n\";\n";
echo "echo \"        })();\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"    },\\n\";\n";
echo "echo \"// The login method hides displays the\\n\";\n";
echo "echo \"    // user's login data and shows the submit form\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"    login : function(name,gravatar){\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        chat.data.name = name;\\n\";\n";
echo "echo \"        chat.data.gravatar = gravatar;\\n\";\n";
echo "echo \"        $('#chatTopBar').html(chat.render('loginTopBar',chat.data));\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        $('#loginForm').fadeOut(function(){\\n\";\n";
echo "echo \"            $('#submitForm').fadeIn();\\n\";\n";
echo "echo \"            $('#chatText').focus();\\n\";\n";
echo "echo \"        });\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"    },\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"    // The render method generates the HTML markup\\n\";\n";
echo "echo \"    // that is needed by the other methods:\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"    render : function(template,params){\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        var arr = [];\\n\";\n";
echo "echo \"        switch(template){\\n\";\n";
echo "echo \"            case 'loginTopBar':\\n\";\n";
echo "echo \"                arr = [\\n\";\n";
echo "echo \"                '<span><img src=\\\"',params.gravatar,'\\\" width=\\\"23\\\" height=\\\"23\\\" />',\\n\";\n";
echo "echo \"                '<span class=\\\"name\\\">',params.name,\\n\";\n";
echo "echo \"                '</span><a href=\\\"\\\" class=\\\"logoutButton rounded\\\">Logout</a></span>'];\\n\";\n";
echo "echo \"            break;\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"            case 'chatLine':\\n\";\n";
echo "echo \"                arr = [\\n\";\n";
echo "echo \"                    '<div class=\\\"chat chat-',params.id,' rounded\\\"><span class=\\\"gravatar\\\">'+\\n\";\n";
echo "echo \"                    '<img src=\\\"',params.gravatar,'\\\" width=\\\"23\\\" height=\\\"23\\\" '+\\n\";\n";
echo "echo \"                    'onload=\\\"this.style.visibility=\\\\'visible\\\\'\\\" />',\\n\";\n";
echo "echo \"                    '</span><span class=\\\"author\\\">',params.author,\\n\";\n";
echo "echo \"                    ':</span><span class=\\\"text\\\">',params.text,\\n\";\n";
echo "echo \"                    '</span><span class=\\\"time\\\">',params.time,'</span></div>'];\\n\";\n";
echo "echo \"                                        <script src=\\\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\\\" integrity=\\\"sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa\\\" crossorigin=\\\"anonymous\\\"></script>\\n\";\n";
echo "echo \"            break;\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"            case 'user':\\n\";\n";
echo "echo \"                arr = [\\n\";\n";
echo "echo \"                    '<div class=\\\"user\\\" title=\\\"',params.name,'\\\"><img src=\\\"',params.gravatar,\\n\";\n";
echo "echo \"                    '\\\" width=\\\"30\\\" height=\\\"30\\\" onload=\\\"this.style.visibility=\\\\'visible\\\\'\\\"'+\\n\";\n";
echo "echo \"                    ' /></div>'\\n\";\n";
echo "echo \"                ];\\n\";\n";
echo "echo \"            break;\\n\";\n";
echo "echo \"        }\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        // A single array join is faster than\\n\";\n";
echo "echo \"        // multiple concatenations\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        return arr.join('');\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"    },\\n\";\n";
echo "echo \"// The addChatLine method ads a chat entry to the page\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"    addChatLine : function(params){\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        // All times are displayed in the user's timezone\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        var d = new Date();\\n\";\n";
echo "echo \"        if(params.time) {\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"            // PHP returns the time in UTC (GMT). We use it to feed the date\\n\";\n";
echo "echo \"            // object and later output it in the user's timezone. JavaScript\\n\";\n";
echo "echo \"            // internally converts it for us.\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"            d.setUTCHours(params.time.hours,params.time.minutes);\\n\";\n";
echo "echo \"        }\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        params.time = (d.getHours() < 10 ? '0' : '' ) + d.getHours()+':'+\\n\";\n";
echo "echo \"                      (d.getMinutes() < 10 ? '0':'') + d.getMinutes();\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        var markup = chat.render('chatLine',params),\\n\";\n";
echo "echo \"            exists = $('#chatLineHolder .chat-'+params.id);\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        if(exists.length){\\n\";\n";
echo "echo \"            exists.remove();\\n\";\n";
echo "echo \"        }\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        if(!chat.data.lastID){\\n\";\n";
echo "echo \"            // If this is the first chat, remove the\\n\";\n";
echo "echo \"            // paragraph saying there aren't any:\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"            $('#chatLineHolder p').remove();\\n\";\n";
echo "echo \"        }\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        // If this isn't a temporary chat:\\n\";\n";
echo "echo \"        if(params.id.toString().charAt(0) != 't'){\\n\";\n";
echo "echo \"            var previous = $('#chatLineHolder .chat-'+(+params.id - 1));\\n\";\n";
echo "echo \"            if(previous.length){\\n\";\n";
echo "echo \"                previous.after(markup);\\n\";\n";
echo "echo \"            }\\n\";\n";
echo "echo \"            else chat.data.jspAPI.getContentPane().append(markup);\\n\";\n";
echo "echo \"        }\\n\";\n";
echo "echo \"        else chat.data.jspAPI.getContentPane().append(markup);\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        // As we added new content, we need to\\n\";\n";
echo "echo \"        // reinitialise the jScrollPane plugin:\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        chat.data.jspAPI.reinitialise();\\n\";\n";
echo "echo \"        chat.data.jspAPI.scrollToBottom(true);\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"    },\\n\";\n";
echo "echo \"// This method requests the latest chats\\n\";\n";
echo "echo \"    // (since lastID), and adds them to the page.\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"    getChats : function(callback){\\n\";\n";
echo "echo \"        $.tzGET('getChats',{lastID: chat.data.lastID},function(r){\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"            for(var i=0;i<r.chats.length;i++){\\n\";\n";
echo "echo \"                chat.addChatLine(r.chats[i]);\\n\";\n";
echo "echo \"            }\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"            if(r.chats.length){\\n\";\n";
echo "echo \"                chat.data.noActivity = 0;\\n\";\n";
echo "echo \"                chat.data.lastID = r.chats[i-1].id;\\n\";\n";
echo "echo \"            }\\n\";\n";
echo "echo \"            else{\\n\";\n";
echo "echo \"                // If no chats were received, increment\\n\";\n";
echo "echo \"                // the noActivity counter.\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"                chat.data.noActivity++;\\n\";\n";
echo "echo \"            }\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"            if(!chat.data.lastID){\\n\";\n";
echo "echo \"                chat.data.jspAPI.getContentPane().html('<p class=\\\"noChats\\\">No chats yet</p>');\\n\";\n";
echo "echo \"            }\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"            // Setting a timeout for the next request,\\n\";\n";
echo "echo \"            // depending on the chat activity:\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"            var nextRequest = 1000;\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"            // 2 seconds\\n\";\n";
echo "echo \"            if(chat.data.noActivity > 3){\\n\";\n";
echo "echo \"                nextRequest = 2000;\\n\";\n";
echo "echo \"            }\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"            if(chat.data.noActivity > 10){\\n\";\n";
echo "echo \"                nextRequest = 5000;\\n\";\n";
echo "echo \"            }\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"            // 15 seconds\\n\";\n";
echo "echo \"            if(chat.data.noActivity > 20){\\n\";\n";
echo "echo \"                nextRequest = 15000;\\n\";\n";
echo "echo \"            }\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"            setTimeout(callback,nextRequest);\\n\";\n";
echo "echo \"        });\\n\";\n";
echo "echo \"    },\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"    // Requesting a list with all the users.\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"    getUsers : function(callback){\\n\";\n";
echo "echo \"        $.tzGET('getUsers',function(r){\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"            var users = [];\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"            for(var i=0; i< r.users.length;i++){\\n\";\n";
echo "echo \"                if(r.users[i]){\\n\";\n";
echo "echo \"                    users.push(chat.render('user',r.users[i]));\\n\";\n";
echo "echo \"                }\\n\";\n";
echo "echo \"            }\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"            var message = '';\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"            if(r.total<1){\\n\";\n";
echo "echo \"                message = 'No one is online';\\n\";\n";
echo "echo \"            }\\n\";\n";
echo "echo \"            else {\\n\";\n";
echo "echo \"                message = r.total+' '+(r.total == 1 ? 'person':'people')+' online';\\n\";\n";
echo "echo \"            }\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"            users.push('<p class=\\\"count\\\">'+message+'</p>');\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"            $('#chatUsers').html(users.join(''));\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"            setTimeout(callback,15000);\\n\";\n";
echo "echo \"        });\\n\";\n";
echo "echo \"    },\\n\";\n";
echo "echo \"/ This method displays an error message on the top of the page:\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"    displayError : function(msg){\\n\";\n";
echo "echo \"        var elem = $('<div>',{\\n\";\n";
echo "echo \"            id        : 'chatErrorMessage',\\n\";\n";
echo "echo \"            html    : msg\\n\";\n";
echo "echo \"        });\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        elem.click(function(){\\n\";\n";
echo "echo \"            $(this).fadeOut(function(){\\n\";\n";
echo "echo \"                $(this).remove();\\n\";\n";
echo "echo \"            });\\n\";\n";
echo "echo \"        });\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        setTimeout(function(){\\n\";\n";
echo "echo \"            elem.click();\\n\";\n";
echo "echo \"        },5000);\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"        elem.hide().appendTo('body').slideDown();\\n\";\n";
echo "echo \"    }\\n\";\n";
echo "echo \"};\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"// Custom GET & POST wrappers:\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"$.tzPOST = function(action,data,callback){\\n\";\n";
echo "echo \"    $.post('php/ajax.php?action='+action,data,callback,'json');\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"$.tzGET = function(action,data,callback){\\n\";\n";
echo "echo \"    $.get('php/ajax.php?action='+action,data,callback,'json');\\n\";\n";
echo "echo \"}\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"// A custom jQuery method for placeholder text:\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"$.fn.defaultText = function(value){\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"    var element = this.eq(0);\\n\";\n";
echo "echo \"    element.data('defaultText',value);\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"    element.focus(function(){\\n\";\n";
echo "echo \"        if(element.val() == value){\\n\";\n";
echo "echo \"            element.val('').removeClass('defaultText');\\n\";\n";
echo "echo \"        }\\n\";\n";
echo "echo \"    }).blur(function(){\\n\";\n";
echo "echo \"        if(element.val() == '' || element.val() == value){\\n\";\n";
echo "echo \"            element.addClass('defaultText').val(value);\\n\";\n";
echo "echo \"        }\\n\";\n";
echo "echo \"    });\\n\";\n";
echo "echo \"\\n\";\n";
echo "echo \"    return element.blur();\\n\";\n";
echo "echo \"}\";\n";
echo "\n";
echo "?>";


